# Generated by Django 3.2.14 on 2022-08-03 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='dictance',
            new_name='distance',
        ),
    ]
