# Generated by Django 3.2.14 on 2022-08-09 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('races', '0003_alter_race_owner'),
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='run',
            name='race',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='races.race'),
        ),
        migrations.AlterUniqueTogether(
            name='run',
            unique_together={('owner', 'race')},
        ),
    ]
