# Generated by Django 3.2.14 on 2022-08-09 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('races', '0003_alter_race_owner'),
        ('stars', '0002_alter_star_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.race'),
        ),
        migrations.AlterUniqueTogether(
            name='star',
            unique_together={('owner', 'race')},
        ),
    ]
